### ISSUE TITLE
Datebase migrations

### ISSUE THREAD

**Issue by deepak-97** [fruxc/Society#2]
I am not to find wings's  table migration

**Comment by mitulmarsonia** [comment]
same issue.

**Comment by mitulmarsonia** [comment]
I realize migration files not committed

**Comment by fruxc** [comment]
There are three tables you need to create manually,
These tables are for dynamic list.
Just create a table named as "wing" with "id" and "name" attribute, "role" with same attributes, and "act" with same attributes.
Wing is for wings in the building, role is for designation of society member and act is for actions which should be taken after any complaint. 
Please let me know if there are more issues.

**Comment by fruxc** [comment]
I have resolved every possible issue that could I find and updated the readme file. Just go through it you'll get all of your answers. Upgraded to Laravel 8 as well :).
